# Generated by Django 2.1.4 on 2018-12-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('VOLKSWAGEN', 'Volkswagen'), ('AUDI', 'Audi')], max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
