# Generated by Django 2.1.4 on 2018-12-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nctbrowse', '0002_auto_20181224_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('ALFA ROMEO', 'Alfa Romeo'), ('ARDAGH', 'Ardagh'), ('ASQUITH', 'Asquith'), ('ASTON MARTIN', 'Aston Martin'), ('AUDI', 'Audi'), ('AUSTIN', 'Austin'), ('AUSTIN ROVER', 'Austin Rover'), ('BADSWORTH', 'Badsworth'), ('BEAUFORD', 'Beauford'), ('BENTLEY', 'Bentley'), ('BINZ', 'Binz'), ('BMW', 'Bmw'), ('BRAMWITH', 'Bramwith'), ('BRENCHLEY', 'Brenchley'), ('BRISTOL', 'Bristol'), ('C I', 'C I'), ('CADILLAC', 'Cadillac'), ('CARBODIES', 'Carbodies'), ('CATERHAM', 'Caterham'), ('CHEVROLET', 'Chevrolet'), ('CHRYSLER', 'Chrysler'), ('CHRYSLER JEEP', 'Chrysler Jeep'), ('CITROEN', 'Citroen'), ('DACIA', 'Dacia'), ('DAEWOO', 'Daewoo'), ('DAIHATSU', 'Daihatsu'), ('DAIMLER', 'Daimler'), ('DATSUN', 'Datsun'), ('DE LOREAN', 'De Lorean'), ('DENNIS', 'Dennis'), ('DODGE', 'Dodge'), ('DUFFY', 'Duffy'), ('FAIRWAY', 'Fairway'), ('FERRARI', 'Ferrari'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('FSO', 'Fso'), ('GMC', 'Gmc'), ('GOWRINGS', 'Gowrings'), ('HOLDEN', 'Holden'), ('HONDA', 'Honda'), ('HUMMER', 'Hummer'), ('HYUNDAI', 'Hyundai'), ('IMPERIAL', 'Imperial'), ('INFINITI', 'Infiniti'), ('INTERNATIONAL', 'International'), ('ISUZU', 'Isuzu'), ('IVECO', 'Iveco'), ('JAGUAR', 'Jaguar'), ('JEEP', 'Jeep'), ('KIA', 'Kia'), ('LADA', 'Lada'), ('LAMBORGHINI', 'Lamborghini'), ('LANCIA', 'Lancia'), ('LANDROVER', 'Landrover'), ('LDV', 'Ldv'), ('LEXUS', 'Lexus'), ('LEYLAND', 'Leyland'), ('LINCOLN', 'Lincoln'), ('LOTUS', 'Lotus'), ('LTI', 'Lti'), ('MAKE UNSPECIFIED', 'Make Unspecified'), ('MASERATI', 'Maserati'), ('MAZDA', 'Mazda'), ('MERCEDES BENZ', 'Mercedes Benz'), ('MERCEDES/COMPASS', 'Mercedes/Compass'), ('METROCAB', 'Metrocab'), ('MG', 'Mg'), ('MICRO-VETT', 'Micro-Vett'), ('MINI', 'Mini'), ('MITSUBISHI', 'Mitsubishi'), ('MITSUOKA', 'Mitsuoka'), ('MORGAN', 'Morgan'), ('MORRIS', 'Morris'), ('NEUSON', 'Neuson'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('OTHER', 'Other'), ('PANTHER', 'Panther'), ('PERODUA', 'Perodua'), ('PEUGEOT', 'Peugeot'), ('PORSCHE', 'Porsche'), ('PROTON', 'Proton'), ('REGENT', 'Regent'), ('RELIANT', 'Reliant'), ('RENAULT', 'Renault'), ('RILEY', 'Riley'), ('ROLLS ROYCE', 'Rolls Royce'), ('ROVER', 'Rover'), ('SAAB', 'Saab'), ('SEAT', 'Seat'), ('SHELSLEY', 'Shelsley'), ('SKODA', 'Skoda'), ('SMART', 'Smart'), ('SSANGYONG', 'Ssangyong'), ('STANDARD MOTOR COMPANY', 'Standard Motor Company'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('TALBOT', 'Talbot'), ('TATA', 'Tata'), ('TESLA', 'Tesla'), ('TIGER', 'Tiger'), ('TOYOTA', 'Toyota'), ('TRABANT', 'Trabant'), ('TRIUMPH', 'Triumph'), ('TVR', 'Tvr'), ('VAUXHALL', 'Vauxhall'), ('VINTAGE MOTOR COMPANY', 'Vintage Motor Company'), ('VOLKSWAGEN', 'Volkswagen'), ('VOLVO', 'Volvo'), ('WESTFIELD', 'Westfield'), ('YUGO', 'Yugo')], max_length=50),
        ),
    ]
