# Generated by Django 2.1.4 on 2018-12-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nctbrowse', '0003_auto_20181224_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=50),
        ),
    ]
