# Generated by Django 2.1.4 on 2018-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nctbrowse', '0004_auto_20181225_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
